name: PhpDocumentor

on:
  workflow_run:
    workflows: ["Unit Tests"]
    branches: [master]
    types:
      - completed

jobs:
  PHPDoc:
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Generate Docs
        run: |
          wget -q https://phpdoc.org/phpDocumentor.phar
          chmod +x phpDocumentor.phar
          ./phpDocumentor.phar run -d src -t docs --visibility public,protected --title $GITHUB_REPOSITORY

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          folder: docs # The folder the action should deploy.
          clean: true # Automatically remove deleted files from the deploy branch

